---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "nexus"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/nexus:${project.version}"
        imagePullPolicy: "IfNotPresent"
        readinessProbe:
          httpGet:
            path: "/content/repositories/"
            port: 8081
          initialDelaySeconds: 60
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: "/content/repositories/"
            port: 8081
          initialDelaySeconds: 180
          timeoutSeconds: 10
          failureThreshold: 3
        name: "nexus"
        ports:
        - containerPort: 8081
          name: "http"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: "/sonatype-work/storage"
          name: "nexus-storage"
          readOnly: false
      volumes:
      - name: "nexus-storage"
        persistentVolumeClaim:
          claimName: nexus-storage
