---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: "gogs"
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "gogs"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      volumes:
      - name: gogs-data
        persistentVolumeClaim:
          claimName: gogs-data
      containers:
      - env:
        - name: "GOGS_SERVER__ROOT_URL"
          valueFrom:
            configMapKeyRef:
              key: "gogs-server--root-url"
              name: "gogs"
        - name: "ADMIN_USER_EMAIL"
          valueFrom:
            configMapKeyRef:
              key: "admin-user-email"
              name: "gogs"
        - name: "ADMIN_USER_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "admin-user-password"
              name: "gogs"
        - name: "ADMIN_USER_CREATE"
          value: "true"
        - name: "GOGS_WEBHOOK__TASK_INTERVAL"
          value: "true"
        - name: "GOGS_WEBHOOK__SKIP_TLS_VERIFY"
          value: "true"
        - name: "ADMIN_USER_NAME"
          valueFrom:
            configMapKeyRef:
              key: "admin-user-name"
              name: "gogs"
        - name: "KUBERNETES_ADMIN_USER"
          valueFrom:
            configMapKeyRef:
              key: "kubernetes-admin-user"
              name: "gogs"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/gogs:${gogs.image.version}"
        imagePullPolicy: "IfNotPresent"
        name: "gogs"
        ports:
        - containerPort: 2222
          name: "ssh"
        - containerPort: 3000
          name: "http"
        volumeMounts:
        - mountPath: /app/gogs/data
          name: gogs-data
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      serviceAccountName: "gogs"
