---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "jenkins"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      annotations:
        fabric8.io/secret-ssh-key: "jenkins-git-ssh,jenkins-master-ssh"
        fabric8.io/secret-ssh-config: "jenkins-ssh-config"
        fabric8.io/secret-gpg-key: "jenkins-release-gpg"
        fabric8.io/secret-maven-settings: "jenkins-maven-settings"
        fabric8.io/secret-hub-api-token: "jenkins-hub-api-token"
        fabric8.io/secret-docker-cfg: "jenkins-docker-cfg"
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - env:
        - name: GIT_COMMITTER_EMAIL
          value: fabric8@googlegroups.com
        - name: GIT_COMMITTER_NAME
          value: fabric8
        - name: "PROJECT_VERSION"
          valueFrom:
            configMapKeyRef:
              key: "project-version"
              name: "jenkins"
        - name: "PIPELINE_ELASTICSEARCH_PROTOCOL"
          valueFrom:
            configMapKeyRef:
              key: "pipeline-elasticsearch-protocol"
              name: "jenkins"
        - name: "JENKINS_GOGS_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "jenkins-gogs-password"
              name: "jenkins"
        - name: "JENKINS_GOGS_USER"
          valueFrom:
            configMapKeyRef:
              key: "jenkins-gogs-user"
              name: "jenkins"
        - name: "JENKINS_GOGS_EMAIL"
          valueFrom:
            configMapKeyRef:
              key: "jenkins-gogs-email"
              name: "jenkins"
        - name: "PIPELINE_ELASTICSEARCH_HOST"
          valueFrom:
            configMapKeyRef:
              key: "pipeline-elasticsearch-host"
              name: "jenkins"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBERNETES_MASTER"
          value: "https://kubernetes.default"
        image: "fabric8/jenkins-docker:${project.version}"
        imagePullPolicy: "IfNotPresent"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
          failureThreshold: 3
        name: "jenkins"
        ports:
        - containerPort: 50000
          name: "slave"
        - containerPort: 8080
          name: "http"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: /var/jenkins_home/jobs
          name: jenkins-jobs
          readOnly: false
        - mountPath: /var/jenkins_home/workspace
          name: jenkins-workspace
          readOnly: false
      serviceAccountName: "jenkins"
      volumes:
      - name: jenkins-jobs
        persistentVolumeClaim:
          claimName: jenkins-jobs
      - name: jenkins-workspace
        persistentVolumeClaim:
          claimName: jenkins-workspace
