---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-letschat/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "hubot-letschat"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "LETSCHAT_HUBOT_USERNAME"
          valueFrom:
            configMapKeyRef:
              name: hubot-letschat
              key: letschat-hubot-username
        - name: "LETSCHAT_HUBOT_PASSWORD"
          valueFrom:
            configMapKeyRef:
              name: hubot-letschat
              key: letschat-hubot-password
        - name: "HUBOT_JENKINS_URL"
          valueFrom:
            configMapKeyRef:
              name: hubot-letschat
              key: hubot-jenkins-url
        - name: "HUBOT_JENKINS_AUTH"
          valueFrom:
            configMapKeyRef:
              name: hubot-letschat
              key: hubot-jenkins-auth
        - name: "HUBOT_LCB_ROOMS"
          valueFrom:
            configMapKeyRef:
              name: hubot-letschat
              key: letschat-default-rooms
        - name: "HUBOT_GRAFANA_HOST"
          valueFrom:
            configMapKeyRef:
              name: hubot-letschat
              key: hubot-grafana-host
        - name: "HUBOT_GRAFANA_API_KEY"
          valueFrom:
            configMapKeyRef:
              name: hubot-letschat
              key: hubot-grafana-api-key
        image: "fabric8/hubot-letschat:v1.0.0"
        name: "hubot-letschat"
        ports:
        - containerPort: 8080
          name: "http"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
