---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    fabric8.io/type: "preview"
  name: "jenkins"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: "fabric8/jenkins-openshift:${jenkins-openshift.version}"
        imagePullPolicy: "Always"
        name: "jenkins"
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/login"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 420
          failureThreshold: 30
          httpGet:
            path: "/login"
            port: 8080
        ports:
        - containerPort: 50000
          name: "slave"
        - containerPort: 8080
          name: "http"
        env:
        - name: OPENSHIFT_ENABLE_OAUTH
          value: "true"
        - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
          value: "true"
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: KUBERNETES_MASTER
          value: "https://kubernetes.default:443"
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkins-home
          readOnly: false
      serviceAccountName: "jenkins"
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home