---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "content-repository"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/caddy-server:${caddy-server.version}"
        imagePullPolicy: "IfNotPresent"
        name: "content-repository"
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 9180
          name: "prometheus"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: "/var/www/html"
          name: "content"
          readOnly: false
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: content-repository